package enttenant

import (
	"context"
	"fmt"

	"entgo.io/ent"

	"gotenancy"
	"gotenancy/data"
)

// Mutation is the storage-level predicate surface generated by Ent mutations.
type Mutation interface {
	Op() ent.Op
	WhereP(...SelectorPredicate)
	Field(string) (ent.Value, bool)
	SetField(string, ent.Value) error
}

// MutationFilter applies tenant guards to Ent mutations.
type MutationFilter struct {
	config Config
}

// NewMutationFilter creates a reusable Ent mutation tenant filter.
func NewMutationFilter(config Config) MutationFilter {
	return MutationFilter{config: config.normalize()}
}

// FilterMutation applies tenant isolation to mutation using config.
func FilterMutation(ctx context.Context, mutation Mutation, config Config) error {
	return NewMutationFilter(config).Apply(ctx, mutation)
}

// Apply guards create mutations and appends tenant predicates to update/delete mutations.
func (filter MutationFilter) Apply(ctx context.Context, mutation Mutation) error {
	if mutation == nil {
		return ErrNilMutation
	}

	config := filter.config.normalize()
	dataFilter, err := data.NewFilter(ctx, config.filterOptions()...)
	if err != nil {
		return err
	}
	if dataFilter.IsHost() {
		return nil
	}

	tenantID, ok := dataFilter.TenantID()
	if !ok {
		return data.ErrNoTenant
	}

	op := mutation.Op()
	switch {
	case op.Is(ent.OpCreate):
		value, ok := mutation.Field(config.TenantField)
		if ok {
			if fmt.Sprint(value) != tenantID.String() {
				return gotenancy.ErrTenantMismatch
			}
			return nil
		}
		if err := mutation.SetField(config.TenantField, tenantID.String()); err != nil {
			return fmt.Errorf("%w: %s: %v", ErrTenantFieldNotFound, config.TenantField, err)
		}
		return nil
	case op.Is(ent.OpUpdate), op.Is(ent.OpUpdateOne), op.Is(ent.OpDelete), op.Is(ent.OpDeleteOne):
		mutation.WhereP(selectorPredicate(config, tenantID))
		return nil
	default:
		return ErrUnsupportedMutation
	}
}

// Hook returns an Ent mutation hook that enforces tenant isolation before mutation execution.
func Hook(config Config) ent.Hook {
	filter := NewMutationFilter(config)
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, mutation ent.Mutation) (ent.Value, error) {
			scoped, ok := mutation.(Mutation)
			if !ok {
				return nil, ErrUnsupportedMutation
			}
			if err := filter.Apply(ctx, scoped); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, mutation)
		})
	}
}
